# Usamos una imagen base de Nginx para servir archivos estáticos
FROM nginx:alpine

# Copiar los archivos de la carpeta local del proyecto al contenedor
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para el servidor web
EXPOSE 80
